[sim]
connections = "1"
delay = "25ms"
streams = "1..200"
max_inflight = 10000000
iterations = 1000
stream_data = "2500..29478216"

[report.rx-packets]
filters = ["conn.success", "conn.client"]
x = "conn.streams"
y = "conn.rx.packets"

[report.lost-packets]
filters = ["conn.success", "conn.client"]
x = "conn.streams"
y = "conn.lost.packets"

[report.rx-throughput]
filters = ["conn.success", "conn.client"]
x = "conn.streams"
y = "conn.rx.stream-throughput"

[report.congestion-window]
filters = ["conn.success", "conn.client"]
x = "conn.streams"
y = "conn.max-cwin"
